<?php /* Smarty version 2.6.25, created on 2009-11-12 00:36:49
         compiled from tpl_head:22 */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/%%19^194^194941AA%%tpl_head%3A22.inc'] = 'eb71102117c31d02fcbd272d493e46c7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_0(&$_smarty)
{
echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_1(&$_smarty)
{
echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_2(&$_smarty)
{
echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_3(&$_smarty)
{
echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_4(&$_smarty)
{
echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_5(&$_smarty)
{
echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_eb71102117c31d02fcbd272d493e46c7_6(&$_smarty)
{
echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
