<?php /* Smarty version 2.6.25, created on 2009-11-12 00:36:49
         compiled from tpl_top:22 */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = '23298517a4bc913279f0438a1789de2f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_23298517a4bc913279f0438a1789de2f_0(&$_smarty)
{
echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
