<?php /* Smarty version 2.6.25, created on 2009-11-08 19:52:11
         compiled from content:content_en */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/15^%%70^707^707A8977%%content%3Acontent_en.inc'] = '064b1c70daaf5f7509d1e017d6d4ba98';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'CompanyDirectory', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_064b1c70daaf5f7509d1e017d6d4ba98_0(&$_smarty)
{
echo $_smarty->_plugins['function']['CompanyDirectory'][0][0]->function_plugin(array('action' => 'categorylist'), $_smarty);
}



?>
