<?php /* Smarty version 2.6.25, created on 2009-12-05 20:37:26
         compiled from module_file_tpl:CGExtensions%3Blisttemplates.tpl */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/CGExtensions^%%27^275^27507CDF%%module_file_tpl%3ACGExtensions%3Blisttemplates.tpl.inc'] = '75a826017e15ad24b674a2c7030a0b0a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:CGExtensions;listtemplates.tpl', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_75a826017e15ad24b674a2c7030a0b0a_0(&$_smarty)
{
echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
