<?php /* Smarty version 2.6.25, created on 2009-12-05 20:36:58
         compiled from module_file_tpl:CompanyDirectory%3Beditcompany.tpl */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/CompanyDirectory^%%95^956^956BF8AC%%module_file_tpl%3ACompanyDirectory%3Beditcompany.tpl.inc'] = '1f5f1224bd3faafa1a7c1d8a2d03cb81';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'module_action_link', 'module_file_tpl:CompanyDirectory;editcompany.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_1f5f1224bd3faafa1a7c1d8a2d03cb81_0(&$_smarty)
{
echo module_action_link(array('module' => 'CGGoogleMaps','action' => 'getgeocode','urlonly' => 1), $_smarty);
}



?>
