<?php /* Smarty version 2.6.25, created on 2009-12-05 20:37:26
         compiled from module_file_tpl:CompanyDirectory%3Bfielddeflist.tpl */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/CompanyDirectory^%%0B^0B2^0B24B471%%module_file_tpl%3ACompanyDirectory%3Bfielddeflist.tpl.inc'] = '02bd3c3e6834ec96c9f6ea4528044d45';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:CompanyDirectory;fielddeflist.tpl', 35, false),)), $this); ?>
<?php
function _smarty_tplfunc_02bd3c3e6834ec96c9f6ea4528044d45_0(&$_smarty)
{
echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
