<?php /* Smarty version 2.6.25, created on 2009-11-08 19:48:33
         compiled from module_db_tpl:News%3BsummarySample */

$this->_cache_serials['/homepages/30/d170410374/htdocs/justbuyit/tmp/templates_c/News^%%18^18E^18E3D89C%%module_db_tpl%3ANews%3BsummarySample.inc'] = '775fab6fcbf74bbe2ad2335c758baeef';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'cms_escape', 'module_db_tpl:News;summarySample', 17, false),array('modifier', 'cms_date_format', 'module_db_tpl:News;summarySample', 22, false),array('function', 'eval', 'module_db_tpl:News;summarySample', 34, false),)), $this); ?>
<?php
function _smarty_tplfunc_775fab6fcbf74bbe2ad2335c758baeef_0(&$_smarty)
{
echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->content), $_smarty);
}


function _smarty_tplfunc_775fab6fcbf74bbe2ad2335c758baeef_1(&$_smarty)
{
echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->extra), $_smarty);
}


function _smarty_tplfunc_775fab6fcbf74bbe2ad2335c758baeef_2(&$_smarty)
{
echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['field']->value), $_smarty);
}



?>
