<ul>
  <li>1.4 - Oct, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
     <li>Added KML Import</li>
     <li>Minor bug fixes.</li>
    </ul>
  </li>

  <li>1.2 - May, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Added latitude and longitude fields.</li>
      <li>Added capability to lookup lattitude and longitude if CGGoogleMap is installed.</li>
      <li>Added search functionality, with zipcode lookup (requires the postcode module).</li>
      <li>Added export to csv functionality.</li>
      <li>Rewrite import from csv functionality.</li>
    </ul>
  </li>
  <li>1.1.8 - April, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Add More Indexes.</li>
    </ul>
  </li>
  <li>1.1.7 - February, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fixed delete company stuff.</li>
    </ul>
  </li>
  <li>1.1.6 - July, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Add the showall parameter to the categorylist action.</li>
      <li>Split out a couple of more files.</li>
    </ul>
  </li>
  <li>1.1.5 - June, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fix a minor issue with preferences</li>
      <li>Fix some queries that were not using cms_db_prefix</li>
    </ul>
  </li>
  <li>1.1.4 - June, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fix to the tabs</li>
      <li>Minor fix to the status field when editing a company.</li>
      <li>Minor fix to the checkbox custom fields when editing a company.</li>
      <li>Fix to CSV Export.</li>
      <li>Fix to the preferences tab.</li>
    </ul>
  </li>
  <li>1.1.3 - February, 2008 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Adds pagination to summary view</li>
      <li>Fixes a problem with pretty urls in summary view</li>
      <li>Fixes a problem with the sort order preferences</li>
      <li>(_SjG) - Implements tsw\'s patch for custom fields in the summary template</li>
    </ul>
  </li>
  <li>1.1.2 - November, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Now use cms_move_uploaded_file instead of move_uploaded_file</li>
      <li>Require CMS 1.2.1 or later</li>
    </ul>
  </li>
  <li>1.1.1 - November, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Fixed a problem with the detail links in summary mode when pretty urls were disabled.</li>
    </ul>
  </li>
  <li>1.1 - September, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Added support for pretty urls</li>
      <li>Filled out the help</li>
      <li>Added a category list mode</li>
      <li>Added support for frontend editing of companies</li>
      <li>Added support for public and admin only fields in companies</li>
      <li>Added different sorting capabilities in summary view</li>
      <li>Changed Minimum CMS Version and added support for the 1.1 series</li>
    </ul>
  </li>
  <li>1.2
    <ul>
      <li>Added support for langitude and longitude, including dynamic lookups from the postcode module.</li>
      <li>Add more indexes to the database for performance</li>
      <li>Import and export CSV work</li>
      <li>Add search including zipcode lookup and bounding box calculations.</li>
    </ul>
  </li>
  <li>1.3 - July, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Added support for pretty urls</li>
      <li>Filled out the help</li>
      <li>Added a category list mode</li>
      <li>Added support for frontend editing of companies</li>
      <li>Added support for public and admin only fields in companies</li>
      <li>Added different sorting capabilities in summary view</li>
      <li>Changed Minimum CMS Version and added support for the 1.1 series</li>
    </ul>
  </li>
  <li>1.3.2 - August, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix minor error in the installer.</li>
      <li>In summary mode, ensure that a company is only output once.</li>
    </ul>  
  </li>
  <li>1.3.3 - August, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix errors with entities in frontend wysiwygs.</li>
      <li>Fix error in bounding box calculation.</li>
      <li>Numerous other small bug fixes.</li>
    </ul>  
  </li>
  <li>1.3.4 - September, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix some more small issues with frontend submit</li>
    </ul>  
  </li>
  <li>1.4.1 - October, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Adds ability to import fields from KML.</li>
      <li>Adds field type to the output for custom fields.</li>
    </ul>  
  </li>
</ul>
